### ISSUE TITLE
uint8 quantization on saving

### ISSUE THREAD

**Issue by neale** [huanzhang12/ZOO-Attack#2]
Hi, 

**Edit** :  the .npy archives work fine, but I can't reproduce this on the .png files

 
I've been using your updated version of the CW L2 attack to generate some images on Imagenet. I was wondering how you tested the images you generated. I noticed that the adversarial perturbations don't seem to survive the saving process, when the images get converted to uint8 and saved to disk. 

If I save them and reload them back they get classified as the same class as the original image. In the original CW paper they mention being able to change the prediction label by only altering the least significant bit in the images, so it makes sense that that quantization would be fatal to the adversarial perturbations. 

Did you have a way around this? 
Thanks.

**Comment by huanzhang12** [comment]
Yes you have to use the .npy files to reproduce the attack. The .png files are for viewing only.

Generating adversarial examples that are robust to quantification, scaling, cropping, etc, is an interesting problem itself. You can checkout this paper: https://arxiv.org/pdf/1707.07397.pdf

**Comment by neale** [comment]
Thanks!
